---
development:
  access_key_id: 0XQXXC6YV2C85DX1BF02
  secret_key: fwLOn0Y/IUXEM8Hk49o7QJV+ryOscbhXRb6CmA5l

production:
  access_key_id: 0XQXXC6YV2C85DX1BF02
  secret_key: fwLOn0Y/IUXEM8Hk49o7QJV+ryOscbhXRb6CmA5l
